name: lara

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]
env:
  # renovate: datasource=github-tags depName=nodejs/node versioning=node
  NODE_VERSION: 20
  MARIADB_PASSWORD: lara

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@546935924a613ee54dad399fc717770ac1f3f34d
      with:
        php-version: '8.0'
    - name: setup database
      uses: shogo82148/actions-setup-mysql@v1.26.0
      with:
       distribution: 'mariadb'
       mysql-version: '10.9'
       root-password: ${{env.MARIADB_PASSWORD}}
    - run: mysql -uroot -p${{env.MARIADB_PASSWORD}} -h127.0.0.1 -e 'create database lara'
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{env.NODE_VERSION}}
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Build npm
      run: npm install && npm run prod
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: lara
        DB_USERNAME: root
        DB_PASSWORD: ${{env.MARIADB_PASSWORD}}
      run: |
        npm install
        php artisan migrate:fresh --seed
        php artisan test
