name: lara

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]
env:
  # renovate: datasource=github-tags depName=nodejs/node versioning=node
  NODE_VERSION: 20
  MARIADB_PASSWORD: lara

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@48e0de2ea6fe020804fef2c54f7730e83c24e30d
      with:
        php-version: '8.0'
    - name: setup database
      uses: shogo82148/actions-setup-mysql@37ce50a0bd540e1bd6d85806f9bdffad2d812d5c # v1.29.0
      with:
       distribution: 'mariadb'
       mysql-version: '10.9'
       root-password: ${{env.MARIADB_PASSWORD}}
    - run: mysql -uroot -p${{env.MARIADB_PASSWORD}} -h127.0.0.1 -e 'create database lara'
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Setup Node
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
      with:
        node-version: ${{env.NODE_VERSION}}
    - name: Cache dependencies
      uses: actions/cache@ab5e6d0c87105b4c9c2047343972218f562e4319 # v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Build npm
      run: npm install && npm run prod
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: lara
        DB_USERNAME: root
        DB_PASSWORD: ${{env.MARIADB_PASSWORD}}
      run: |
        npm install
        php artisan migrate:fresh --seed
        php artisan test
